CREATE TABLE medicines (
    id                    BIGINT         NOT NULL AUTO_INCREMENT,
    name                  VARCHAR(150)   NOT NULL,
    generic_name          VARCHAR(150)   NULL,
    brand_name            VARCHAR(150)   NULL,
    description           VARCHAR(2000)  NULL,
    category_id           BIGINT         NOT NULL,
    manufacturer          VARCHAR(150)   NULL,
    price                 DECIMAL(10,2)  NOT NULL,
    prescription_required BOOLEAN        NOT NULL DEFAULT FALSE,
    dosage_information    VARCHAR(255)   NULL,
    expiry_date           DATE           NULL,
    active                BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at            DATETIME(6)    NOT NULL,
    updated_at            DATETIME(6)    NOT NULL,
    PRIMARY KEY (id),
    KEY idx_medicines_category (category_id),
    KEY idx_medicines_name (name),
    KEY idx_medicines_generic (generic_name),
    CONSTRAINT fk_medicines_category FOREIGN KEY (category_id) REFERENCES categories (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;