CREATE TABLE orders (
    id             BIGINT        NOT NULL AUTO_INCREMENT,
    order_number   VARCHAR(30)   NOT NULL,
    customer_id    BIGINT        NOT NULL,
    address_label  VARCHAR(40)   NULL,
    address_line1  VARCHAR(160)  NOT NULL,
    address_line2  VARCHAR(160)  NULL,
    address_city   VARCHAR(80)   NOT NULL,
    address_state  VARCHAR(80)   NOT NULL,
    postal_code    VARCHAR(15)   NOT NULL,
    address_country VARCHAR(60)  NOT NULL,
    subtotal       DECIMAL(10,2) NOT NULL DEFAULT 0,
    tax            DECIMAL(10,2) NOT NULL DEFAULT 0,
    delivery_fee   DECIMAL(10,2) NOT NULL DEFAULT 0,
    discount       DECIMAL(10,2) NOT NULL DEFAULT 0,
    total_amount   DECIMAL(10,2) NOT NULL DEFAULT 0,
    status         VARCHAR(25)   NOT NULL DEFAULT 'PENDING',
    note           VARCHAR(500)  NULL,
    created_at     DATETIME(6)   NOT NULL,
    updated_at     DATETIME(6)   NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_orders_order_number (order_number),
    KEY idx_orders_customer (customer_id),
    KEY idx_orders_status (status),
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE order_items (
    id                    BIGINT        NOT NULL AUTO_INCREMENT,
    order_id              BIGINT        NOT NULL,
    medicine_id           BIGINT        NOT NULL,
    medicine_name         VARCHAR(150)  NOT NULL,
    unit_price            DECIMAL(10,2) NOT NULL,
    quantity              INT           NOT NULL,
    total_price           DECIMAL(10,2) NOT NULL,
    prescription_required BOOLEAN       NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id),
    KEY idx_order_items_order (order_id),
    KEY idx_order_items_medicine (medicine_id),
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_medicine FOREIGN KEY (medicine_id) REFERENCES medicines (id),
    CONSTRAINT chk_order_items_quantity_positive CHECK (quantity > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;