-- V2__seed.sql — MediCare Pharmacy seed data (PostgreSQL)
--
-- Demo credentials (password for ALL three users is literally: password):
--   admin@medicare.com      / password  (ADMIN)
--   pharmacist@medicare.com / password  (PHARMACIST)
--   customer@medicare.com   / password  (CUSTOMER)
--
-- Password hash below is a BCrypt cost-10 hash for "password" generated by
-- this project's own BCryptPasswordEncoder (verified live on 2026-09-21).
--   $2a$10$1Ft7Cjk0H0VHJqPqtmukeua8ZLF2nvg5dK1WboVCHCt8EhZ0Xy8fi
-- Spring Security BCryptPasswordEncoder.matches("password", <hash>) == true.

-- ================= categories =================
INSERT INTO categories (name, description) VALUES
    ('Tablets', 'Oral solid dosage tablets for common ailments'),
    ('Syrups', 'Liquid formulations, cough and cold relief'),
    ('Antibiotics', 'Prescription-only antibiotics'),
    ('Vitamins', 'Vitamins, minerals and nutritional supplements'),
    ('Personal Care', 'Everyday personal care and rehydration essentials')
ON CONFLICT (name) DO NOTHING;

-- ================= users =================
-- All passwords = "password" (BCrypt cost 10, see header comment).
INSERT INTO users (name, email, password, phone, address, role, enabled, created_at, updated_at) VALUES
    ('Admin', 'admin@medicare.com', '$2a$10$1Ft7Cjk0H0VHJqPqtmukeua8ZLF2nvg5dK1WboVCHCt8EhZ0Xy8fi', '9999999999', 'MediCare HQ', 'ADMIN', TRUE, now(), now()),
    ('Pharmacist', 'pharmacist@medicare.com', '$2a$10$1Ft7Cjk0H0VHJqPqtmukeua8ZLF2nvg5dK1WboVCHCt8EhZ0Xy8fi', '8888888888', 'MediCare Pharmacy Store', 'PHARMACIST', TRUE, now(), now()),
    ('Customer', 'customer@medicare.com', '$2a$10$1Ft7Cjk0H0VHJqPqtmukeua8ZLF2nvg5dK1WboVCHCt8EhZ0Xy8fi', '7777777777', '123 Main Street', 'CUSTOMER', TRUE, now(), now())
ON CONFLICT (email) DO NOTHING;

-- ================= medicines (8 rows) =================
INSERT INTO medicines (name, generic_name, brand_name, description, manufacturer, price, prescription_required, category_id, image_url, active, created_at, updated_at) VALUES
    ('Paracetamol 500mg', 'Paracetamol', 'Crocin', 'Fever and mild pain relief, 15 tablets strip', 'GSK', 25.00, FALSE, (SELECT id FROM categories WHERE name = 'Tablets'), NULL, TRUE, now(), now()),
    ('Ibuprofen 200mg', 'Ibuprofen', 'Brufen', 'NSAID for pain and inflammation, 15 tablets strip', 'Abbott', 40.00, FALSE, (SELECT id FROM categories WHERE name = 'Tablets'), NULL, TRUE, now(), now()),
    ('Vitamin C 1000mg', 'Ascorbic Acid', 'Limcee', 'Immunity-boosting chewable tablets, 20 tablets', 'Abbott', 199.00, FALSE, (SELECT id FROM categories WHERE name = 'Vitamins'), NULL, TRUE, now(), now()),
    ('Cetirizine 10mg', 'Cetirizine', 'Zyrtec', 'Anti-allergic for cold, sneezing and itching, 10 tablets', 'Dr. Reddy''s', 60.00, FALSE, (SELECT id FROM categories WHERE name = 'Tablets'), NULL, TRUE, now(), now()),
    ('Amoxicillin 500mg', 'Amoxicillin', 'Moxikind', 'Broad-spectrum antibiotic, 10 capsules — prescription required', 'Mankind', 120.00, TRUE, (SELECT id FROM categories WHERE name = 'Antibiotics'), NULL, TRUE, now(), now()),
    ('Azithromycin 500mg', 'Azithromycin', 'Azithral', 'Macrolide antibiotic, 5 tablets — prescription required', 'Alembic', 180.00, TRUE, (SELECT id FROM categories WHERE name = 'Antibiotics'), NULL, TRUE, now(), now()),
    ('Cough Relief Syrup 150ml', 'Dextromethorphan + Chlorpheniramine', 'Benadryl', 'Dry and wet cough relief syrup, 150ml bottle', 'Johnson & Johnson', 95.00, FALSE, (SELECT id FROM categories WHERE name = 'Syrups'), NULL, TRUE, now(), now()),
    ('ORS Powder 21.5g', 'Oral Rehydration Salts', 'Electral', 'WHO-formula rehydration powder sachet, 21.5g', 'FDC', 30.00, FALSE, (SELECT id FROM categories WHERE name = 'Personal Care'), NULL, TRUE, now(), now())
ON CONFLICT DO NOTHING;

-- ================= inventory =================
-- One item (Cetirizine 10mg, quantity 3) is deliberately low-stock (<= reorder_level 10)
-- to demo the low-stock alert.
INSERT INTO inventory (medicine_id, quantity, reserved_quantity, reorder_level, updated_at) VALUES
    ((SELECT id FROM medicines WHERE name = 'Paracetamol 500mg'), 100, 0, 10, now()),
    ((SELECT id FROM medicines WHERE name = 'Ibuprofen 200mg'), 50, 0, 10, now()),
    ((SELECT id FROM medicines WHERE name = 'Vitamin C 1000mg'), 75, 0, 10, now()),
    ((SELECT id FROM medicines WHERE name = 'Cetirizine 10mg'), 3, 0, 10, now()),
    ((SELECT id FROM medicines WHERE name = 'Amoxicillin 500mg'), 40, 0, 10, now()),
    ((SELECT id FROM medicines WHERE name = 'Azithromycin 500mg'), 25, 0, 10, now()),
    ((SELECT id FROM medicines WHERE name = 'Cough Relief Syrup 150ml'), 60, 0, 10, now()),
    ((SELECT id FROM medicines WHERE name = 'ORS Powder 21.5g'), 200, 0, 10, now())
ON CONFLICT (medicine_id) DO NOTHING;
